---
# Ansible playbook for Windows connections using Kerberos authentication
- name: Connect to Windows with Kerberos Auth
  hosts: all
  gather_facts: false
  vars:
    kerberos_principal: "{{ ansible_user }}@EXAMPLE.COM"
    ansible_connection: ssh
    ansible_shell_type: powershell
    
    tasks:
    - name: Obtain Kerberos TGT using kinit
      ansible.builtin.shell: kinit {{ kerberos_principal }}
      delegate_to: localhost
      changed_when: false
      
    - name: Display obtained Kerberos tickets
      ansible.builtin.shell: klist
      delegate_to: localhost
      register: klist_output
      changed_when: false
      
    - name: Output TGT information
      ansible.builtin.debug:
        var: klist_output.stdout_lines
      
    - name: Verify connection to Windows machine
      ansible.windows.win_ping:
      
    - name: Get system information
      ansible.windows.win_shell: |
        $system_params = @{
          computer_name = $env:COMPUTERNAME
          class = 'Win32_OperatingSystem'
        }
        Get-WmiObject @system_params | Select-Object Caption, Version, OSArchitecture
      register: system_info
      
    - name: Display system information
      ansible.builtin.debug:
        var: system_info.stdout_lines
