---
# Ansible playbook for Windows connections using Kerberos authentication
- name: Connect to Windows with Kerberos Auth
  hosts: windows_servers
  gather_facts: false
  vars:
    kerberos_principal: {{ ansible_user }}
    ansible_connection: ssh
    ansible_shell_type: powershell
  
  pre_tasks:
    - name: Obtain Kerberos TGT using kinit
      ansible.builtin.shell: kinit {{ kerberos_principal }}
      delegate_to: localhost
      changed_when: false
      
  tasks:
    - name: Verify connection to Windows machine
      ansible.windows.win_ping:
      
    - name: Get system information
      ansible.windows.win_shell: |
        $system_params = @{
          computer_name = $env:COMPUTERNAME
          class = 'Win32_OperatingSystem'
        }
        Get-WmiObject @system_params | Select-Object Caption, Version, OSArchitecture
      register: system_info
      
    - name: Display system information
      ansible.builtin.debug:
        var: system_info.stdout_lines
