---
 - name: obtain kerberos ticket for ssh
 pre_tasks:
    - name: run kinit
    local_action: shell kinit '{{ ansible_user }}'

 - name: test kerberos authentication over ssh
  hosts: all
  connection: ssh
  gather_facts: true
  vars:
    ansible_ssh_common_args: -o GSSAPIDelegateCredentials=yes
  tasks:
  - name: win ping
    win_ping:
