---
# First play runs locally to obtain Kerberos TGT
- name: Obtain Kerberos TGT
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    kerberos_principal: "{{ ansible_user }}"
    # Store this in an encrypted vault file, not in the playbook
    kerberos_password: "{{ ansible_password }}"
  
  tasks:
    - name: Obtain Kerberos TGT using kinit with password
      ansible.builtin.shell: echo "{{ kerberos_password }}" | kinit {{ kerberos_principal }}
      no_log: true # to avoid exposing password
      changed_when: false
      
    - name: Display obtained Kerberos tickets
      ansible.builtin.shell: klist
      register: klist_output
      changed_when: false
      
    - name: Output TGT information
      ansible.builtin.debug:
        var: klist_output.stdout_lines

# Second play connects to Windows hosts
- name: Connect to Windows with Kerberos Auth
  hosts: all
  gather_facts: true
  vars:
    ansible_connection: ssh
    ansible_shell_type: powershell
    ansible_ssh_common_args: '-o GSSAPIAuthentication=yes -o GSSAPIDelegateCredentials=yes -vvv'
    ansible_port: 22
  
  tasks:
    - name: Verify connection to Windows machine
      ansible.windows.win_ping:
