---
# First play runs locally to obtain Kerberos TGT
- name: Obtain Kerberos TGT
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    kerberos_principal: "{{ ansible_user }}"
    kerberos_password: "{{ ansible_password }}"
  
  tasks:
    - name: Obtain Kerberos TGT using kinit with password
      ansible.builtin.expect:
        command: kinit {{ kerberos_principal }}
        responses:
          "Password for {{ kerberos_principal }}:": "{{ kerberos_password }}"
        timeout: 30
      no_log: true
      changed_when: false
      
    - name: Display obtained Kerberos tickets
      ansible.builtin.shell: klist
      register: klist_output
      changed_when: false
      
    - name: Output TGT information
      ansible.builtin.debug:
        var: klist_output.stdout_lines

# Second play connects to Windows hosts
- name: Connect to Windows with Kerberos Auth
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: ssh
    ansible_shell_type: powershell
  
  tasks:
    - name: Verify connection to Windows machine
      ansible.windows.win_ping:
      
    - name: Get system information
      ansible.windows.win_shell: |
        $system_params = @{
          computer_name = $env:COMPUTERNAME
          class = 'Win32_OperatingSystem'
        }
        Get-WmiObject @system_params | Select-Object Caption, Version, OSArchitecture
      register: system_info
      
    - name: Display system information
      ansible.builtin.debug:
        var: system_info.stdout_lines
